package com.bot.entity

enum class State(val value: String) {
	HELLO("HELLO"),
	CREATE_CUSTOMER("CREATE_CUSTOMER"), CREATE_REQUEST("CREATE_REQUEST"), MY_REQUESTS("MY_REQUESTS"),
	PENDING_REQUESTS("PENDING_REQUESTS"), MANAGE_BROKERS("MANAGE_BROKERS"),
	MANAGE_USERS("MANAGE_USERS"), MANAGE_SPECIALISTS("MANAGE_SPECIALISTS")
}